name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      couchdb:
        image: couchdb
        ports:
          - 25984:5984

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run netstat
        run: netstat -antp | grep 5984
        
      - name: Connect to CouchDB service
        run: curl http://localhost:25984


